page_size: 10
desc_size: 5
status:
  view:  "View"
  start: "Start"
  testing: "Testing"
model:
  question:
    choose_one: "You have to choose one correct answer!"
test_quest:
  num: 20
question:
  content_length: 300
